export const allTextureKeys = {
  apple: "apple",
  grass_64: "grass_64",
  play_button: "play_button",
  snake_body_bend_down_left: "snake_body_bend_down_left",
  snake_body_bend_down_right: "snake_body_bend_down_right",
  snake_body_bend_left_down: "snake_body_bend_left_down",
  snake_body_bend_left_up: "snake_body_bend_left_up",
  snake_body_bend_right_down: "snake_body_bend_right_down",
  snake_body_bend_right_up: "snake_body_bend_right_up",
  snake_body_bend_up_left: "snake_body_bend_up_left",
  snake_body_bend_up_right: "snake_body_bend_up_right",
  snake_body_down: "snake_body_down",
  snake_body_left: "snake_body_left",
  snake_body_right: "snake_body_right",
  snake_body_up: "snake_body_up",
  snake_head_down: "snake_head_down",
  snake_head_left: "snake_head_left",
  snake_head_right: "snake_head_right",
  snake_head_up: "snake_head_up",
  snake_tail_down: "snake_tail_down",
  snake_tail_left: "snake_tail_left",
  snake_tail_right: "snake_tail_right",
  snake_tail_up: "snake_tail_up",
  start_screen_bg: "start_screen_bg",
  end_screen_bg: "end_screen_bg",
};

const appTextures = {
  [allTextureKeys.apple]: 'apple.png',
  [allTextureKeys.grass_64]: 'grass_64.png',
  [allTextureKeys.play_button]: 'play_button.png',
  [allTextureKeys.snake_body_bend_down_left]: 'snake_body_bend_down_left.png',
  [allTextureKeys.snake_body_bend_down_right]: 'snake_body_bend_down_right.png',
  [allTextureKeys.snake_body_bend_left_down]: 'snake_body_bend_left_down.png',
  [allTextureKeys.snake_body_bend_left_up]: 'snake_body_bend_left_up.png',
  [allTextureKeys.snake_body_bend_right_down]: 'snake_body_bend_right_down.png',
  [allTextureKeys.snake_body_bend_right_up]: 'snake_body_bend_right_up.png',
  [allTextureKeys.snake_body_bend_up_left]: 'snake_body_bend_up_left.png',
  [allTextureKeys.snake_body_bend_up_right]: 'snake_body_bend_up_right.png',
  [allTextureKeys.snake_body_down]: 'snake_body_down.png',
  [allTextureKeys.snake_body_left]: 'snake_body_left.png',
  [allTextureKeys.snake_body_right]: 'snake_body_right.png',
  [allTextureKeys.snake_body_up]: 'snake_body_up.png',
  [allTextureKeys.snake_head_down]: 'snake_head_down.png',
  [allTextureKeys.snake_head_left]: 'snake_head_left.png',
  [allTextureKeys.snake_head_right]: 'snake_head_right.png',
  [allTextureKeys.snake_head_up]: 'snake_head_up.png',
  [allTextureKeys.snake_tail_down]: 'snake_tail_down.png',
  [allTextureKeys.snake_tail_left]: 'snake_tail_left.png',
  [allTextureKeys.snake_tail_right]: 'snake_tail_right.png',
  [allTextureKeys.snake_tail_up]: 'snake_tail_up.png',
  [allTextureKeys.start_screen_bg]: 'start_screen_bg.png',
  [allTextureKeys.end_screen_bg]: 'end_screen_bg.png',
};

export default appTextures;
